{"name": "test_add[int]", "status": "broken", "statusDetails": {"message": "NameError: name 'add_function' is not defined", "trace": "a = 3, b = 5, expected = 8\n\n    @pytest.mark.parametrize(\"a,b,expected\",\n                             [(3,5,8),\n                              (-1,-2,-3),\n                              (100000,100000,200000)\n                              ],ids = [\"int\",\"minus\",\"bigint\"]\n                             )\n    def test_add(a,b,expected):\n>       assert  add_function(a,b) == expected\nE       NameError: name 'add_function' is not defined\n\ntest_parametrize.py:23: NameError"}, "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "8"}], "start": 1618644932436, "stop": 1618644932437, "uuid": "a6864a7f-3652-4059-a9f9-af0c2f332299", "historyId": "c9373e829d7b912254c240635f5d0494", "testCaseId": "6f41edd1e423772ab3257ab38ec97795", "fullName": "test_parametrize#test_add", "labels": [{"name": "suite", "value": "test_parametrize"}, {"name": "host", "value": "BY-20190922YINQ"}, {"name": "thread", "value": "13396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_parametrize"}]}